### ISSUE TITLE
Gauge64 is an unfortunate typo

### ISSUE THREAD

**Issue by ggreif** [chemist/snmp#9]
`Gaude32` should probably be renamed to `Gauge32`. I know it is a breaking change, but this constructor has a big confusion potential when left as is.

**Comment by chemist** [comment]
Upps...., You are right.

**Comment by ggreif** [comment]
Do you accept a pull request?

**Comment by chemist** [comment]
Yes of course. Welcome.

**Comment by ggreif** [comment]
I just discovered the issue title is even more disturbing. Should be "Gaude32 is an unfortunate typo". Must have been totally carried away. Sorry for that.

**Comment by chemist** [comment]
Up version for snmp, fix agentx and up version too.
